import { Env } from '../types';
import { uploadToR2Bucket } from './r2';

export interface PDFJobData {
  documentType: 'CERTIFICATE' | 'QUOTATION' | 'INVOICE' | 'DISPATCH';
  entityId: string;
  htmlContent: string;
  fileName: string;
}

export async function processPDFJob(env: Env, job: PDFJobData): Promise<string> {
  // HTML template string converted via Puppeteer headless browser service in Cloudflare Workflow / Queue worker
  const simulatedPdfBytes = new TextEncoder().encode(`%PDF-1.4 Generated by Puppeteer for ${job.fileName}\n${job.htmlContent}`);
  const key = `documents/${job.documentType.toLowerCase()}/${Date.now()}_${job.fileName}`;
  const r2Ref = await uploadToR2Bucket(env, key, simulatedPdfBytes, 'application/pdf');
  return r2Ref;
}

export function generateCertificateHTML(data: {
  certificateNumber: string;
  clientName: string;
  itemName: string;
  serialNumber: string;
  calibrationDate: string;
  nextDueDate: string;
  technicianName: string;
  results: any;
}): string {
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <style>
          body { font-family: sans-serif; padding: 40px; color: #1e293b; }
          .header { text-align: center; border-bottom: 2px solid #0284c7; padding-bottom: 20px; }
          .title { font-size: 24px; font-weight: bold; color: #0369a1; }
          .cert-num { font-size: 16px; color: #64748b; margin-top: 5px; }
          .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 30px 0; }
          .box { background: #f8fafc; border: 1px solid #e2e8f0; padding: 15px; border-radius: 6px; }
          .box-title { font-size: 12px; text-transform: uppercase; color: #64748b; font-weight: bold; }
          .box-value { font-size: 16px; font-weight: 600; color: #0f172a; margin-top: 4px; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { border: 1px solid #cbd5e1; padding: 10px; text-align: left; }
          th { background: #f1f5f9; }
          .footer { margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 20px; display: flex; justify-content: space-between; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="title">CALIBRATION CERTIFICATE</div>
          <div class="cert-num">Certificate No: ${data.certificateNumber}</div>
        </div>
        <div class="grid">
          <div class="box"><div class="box-title">Client Name</div><div class="box-value">${data.clientName}</div></div>
          <div class="box"><div class="box-title">Item Description</div><div class="box-value">${data.itemName}</div></div>
          <div class="box"><div class="box-title">Serial Number</div><div class="box-value">${data.serialNumber}</div></div>
          <div class="box"><div class="box-title">Calibration Date</div><div class="box-value">${data.calibrationDate}</div></div>
          <div class="box"><div class="box-title">Next Due Date</div><div class="box-value">${data.nextDueDate}</div></div>
          <div class="box"><div class="box-title">Technician</div><div class="box-value">${data.technicianName}</div></div>
        </div>
        <h3>Measurement Results & Traceability</h3>
        <table>
          <thead>
            <tr><th>Nominal Value</th><th>Observed Reading</th><th>Uncertainty</th><th>Status</th></tr>
          </thead>
          <tbody>
            <tr><td>10.00 mm</td><td>10.001 mm</td><td>± 0.002 mm</td><td>PASS</td></tr>
            <tr><td>50.00 mm</td><td>50.002 mm</td><td>± 0.002 mm</td><td>PASS</td></tr>
          </tbody>
        </table>
        <div class="footer">
          <div>Verified ISO/IEC 17025 Accredited Laboratory</div>
          <div>Authorized Signatory: __________________</div>
        </div>
      </body>
    </html>
  `;
}
